---
title: "Lab 6"
author: "Alison Fowler"
date: "9/28/2020"
output: html_document
---

# COVID cases as of September 26, 2020

```{r, echo = FALSE, error = FALSE, warning = FALSE, message = FALSE}
library(RColorBrewer)
library(plotly)
library(tidyverse)
library(maps)
library(mapdata)
library(lubridate)
library(viridis)
library(wesanderson)
```

```{r, echo = FALSE, error = FALSE, warning = FALSE, message = FALSE}

#1. For the above graph “World COVID-19 Confirmed case” summarize the counts for each Country on the graph and update the graph to 9/26/2020. You may need to adjust the size of the points.

library(tidyverse)
# read in the data 
daily_report_09_26 <- read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/09-26-2020.csv")) %>% 
  rename(Long = "Long_") 
```

```{r, echo = FALSE, error = FALSE, warning = FALSE, message = FALSE}
ggplot(daily_report_09_26, aes(x = Long, y = Lat, size = Confirmed/1000)) +
  borders("world", colour = NA, fill = "grey90") +
  theme_bw() +
  geom_point(shape = 21, color='purple', fill='purple', alpha = 0.5) +
  labs(title = 'World COVID-19 Confirmed cases',x = '', y = '',
       size="Cases (x1000))") +
  theme(legend.position = "right") +
  coord_fixed(ratio=1.5)
```

```{r , echo = FALSE, error = FALSE, warning = FALSE, message = FALSE}
# 2. Update Anisa Dhana’s graph layout of the US to 9/26/2020. You may need to adjust the size of the points.

US_report <- daily_report_09_26 %>% 
  filter(Country_Region == "US") %>% 
  filter (!Province_State %in% c("Alaska","Hawaii", "American Samoa",
                                 "Puerto Rico","Northern Mariana Islands", 
                                 "Virgin Islands", "Recovered", "Guam", "Grand Princess",
                                 "District of Columbia", "Diamond Princess"))

mybreaks <- c(1, 100, 1000, 10000, 100000)

ggplot(US_report, aes(x = Long, y = Lat)) +
  borders("state", 
          colour = "white", 
          fill = "grey90") +
  geom_point(aes(x=Long, y=Lat,
                 color=Confirmed),
             stroke=F, 
             alpha=0.5,
             size = 2) +
  scale_size_continuous(name="Cases", 
                        trans="log", 
                        range=c(1,7), 
                        breaks=mybreaks, 
                        labels = c("1-99", "100-999", "1,000-9,999", "10,000-99,999", "100,000+")) +
  scale_color_viridis_c(option="viridis",
                        name="Cases",
                        trans="log", 
                        breaks=mybreaks, 
                        labels = c("1-99", "100-999", "1,000-9,999", "10,000-99,999", "100,000+"))  +
  # Cleaning up the graph
  
  theme_void() + 
  guides( colour = guide_legend()) +
  labs(title = "Anisa Dhana's lagout for COVID-19 Confirmed Cases in the Continental US'") +
  theme(
    legend.position = "bottom",
    text = element_text(color = "#22211d"),
    plot.background = element_rect(fill = "#ffffff", color = NA), 
    panel.background = element_rect(fill = "#ffffff", color = NA), 
    legend.background = element_rect(fill = "#ffffff", color = NA)
  ) +
  coord_fixed(ratio=1.5)
```

```{r, echo = FALSE, error = FALSE, warning = FALSE, message = FALSE}

# 3. Update the above graph “Number of Confirmed Cases by US County” to 9/26/2020 and use a different color scheme or theme. 

report_09_26_2020 <-   read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/04-02-2020.csv")) %>% 
  rename(Long = "Long_") %>% 
  unite(Key, Admin2, Province_State, sep = ".") %>% 
  group_by(Key) %>% 
  summarize(Confirmed = sum(Confirmed)) %>% 
  mutate(Key = tolower(Key))

# get and format the map data
us <- map_data("state")

counties <- map_data("county") %>% 
  unite(Key, subregion, region, sep = ".", remove = FALSE)

# Join the 2 tibbles
state_join <- left_join(counties, report_09_26_2020, by = c("Key"))

# sum(is.na(state_join$Confirmed))

ggplot(data = us, mapping = aes(x = long, y = lat, group = group)) + 
  coord_fixed(1.3) + 
  # Add data layer
  borders("state", colour = "black") +
  geom_polygon(data = state_join, aes(fill = Confirmed)) +
  scale_fill_gradientn(colors = brewer.pal(n = 5, name = "YlOrRd"),
                       breaks = c(1, 10, 100, 1000, 10000, 100000),
                       trans = "log10", na.value = "White") +
  ggtitle("Number of Confirmed Cases by US County") +
  theme_bw() 
```

```{r, echo = FALSE, error = FALSE, warning = FALSE, message = FALSE}
# look at the DC, Maryland, Virginia area
# 4. Make an interactive plot using a state of your chosing using a theme different from used in the above exammples.
daily_report_DMV <-   read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/09-26-2020.csv")) %>% 
  rename(Long = "Long_") %>% 
  filter(Province_State %in% c("Virginia",
                               "District of Columbia",
                               "Maryland")) %>% 
  group_by(Admin2) %>% 
  summarize(Confirmed = sum(Confirmed)) %>% 
  mutate(Admin2 = tolower(Admin2))

us <- map_data("state")
dmv_us <- subset(us, region == c("virginia",
                               "district of columbia",
                               "maryland"))
counties <- map_data("county")
dmv_county <- subset(counties, region == c("virginia",
                                           "district of columbia",
                                           "maryland"))

state_join_4 <- left_join(dmv_county, daily_report_DMV, by = c("subregion" = "Admin2")) 

# plot map
ggplot(data = dmv_county, mapping = aes(x = long, y = lat, group = group)) + 
  coord_fixed(1.3) + 
  # Add data layer
  geom_polygon(data = state_join_4, aes(fill = Confirmed), color = "white") +
  scale_fill_gradientn(colors = brewer.pal(n = 8, name = "YlOrRd"),
                       trans = "log10") +
  labs(title = "COVID-19 Confirmed Cases in DC, Maryland, and Virginia")
```

Interactive Plot: Hover over the counties to see how many confirmed cases they have. 

```{r, echo = FALSE, error = FALSE, warning = FALSE, message = FALSE}
# Interactive Plot 
ggplotly(
  ggplot(data = dmv_county, mapping = aes(x = long, y = lat, group = group)) + 
    coord_fixed(1.3) + 
    # Add data layer
    geom_polygon(data = state_join_4, aes(fill = Confirmed), color = "black") +
    scale_fill_gradientn(colours = wes_palette("Zissou1", 100, type = "continuous")) +
    ggtitle("COVID-19 Cases in DC, Maryland, and Virginia") +
    # Cleaning up the graph
    labs(x=NULL, y=NULL) +
    theme(panel.border = element_blank()) +
    theme(panel.background = element_blank()) +
    theme(axis.ticks = element_blank()) +
    theme(axis.text = element_blank())
)
```
